name: Java CI without Build Tool

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
	  distribution: 'adopt'  # Specify the distribution (adopt, openjdk, zulu, etc.)

      - name: Compile Java Application
        run: javac -d ./build src/simplejavacalculator.java

      - name: Run Java Application
        run: java -cp ./build SimpleJavaCalculator
